build:
  stage: build
  image: microsoft/dotnet:2.2-sdk
  script:
  - dotnet build PerformanceLogger
  - dotnet build Sample
  artifacts:
    untracked: true
    expire_in: 1 day


# Runs the sample project, making sure it doesn't crash at runtime
sample-test:
  stage: test
  image: microsoft/dotnet:2.2-sdk
  script:
  - dotnet run --project Sample
  artifacts:
    untracked: true
    expire_in: 1 day
